### ISSUE TITLE
User is unable to login after logout

### ISSUE THREAD

**Issue by georgepadayatti** [decentralised-dataexchange/data4diabetes-app#269]
User is unable to login after logout. It says invalid mobile number.

**Comment by lijogeorgep** [comment]
@georgepadayatti I am not able to regenerate this issue. For me its working.

**Comment by georgepadayatti** [comment]
> @georgepadayatti I am not able to regenerate this issue. For me its working.

Will check on my end. It was encountered by @lalc in 2024.1.1.

**Comment by lalc** [comment]
Here is the video https://github.com/decentralised-dataexchange/data4diabetes-app/assets/455274/55ff64d2-b4a9-4ef8-b654-b11f5ae2330e

**Comment by deka2024** [comment]
Here is more details about what I described in the meeting. 
As we discussed, it is important to have the consistency throughout the whole platform. Perhaps we could try to find out what the standard is.

In order to avoid miss matches we must make sure we save the numbers in the exact same format everywhere in the system. How we display it can be changed depending on what we find out to be the standard. 

![Image](https://github.com/decentralised-dataexchange/data4diabetes-app/assets/155434128/072c2ab5-cc22-4a7a-b83d-49728d953481)
