### ISSUE TITLE
App store connect issue on push notification

### ISSUE THREAD

**Issue by josmilan** [decentralised-dataexchange/data4diabetes-app#80]
We identified one or more issues with a recent delivery for your app, "Data4Diabetis" 1.0.1 (7). Your delivery was successful, but you may wish to correct the following issues in your next delivery:ITMS-90078: Missing Push Notification Entitlement - Your app appears to register with the Apple Push Notification service, but the app signature's entitlements do not include the 'aps-environment' entitlement. If your app uses the Apple Push Notification service, make sure your App ID is enabled for Push Notification in the Provisioning Portal, and resubmit after signing your app with a Distribution provisioning profile that includes the 'aps-environment' entitlement. Xcode does not automatically copy the aps-environment entitlement from provisioning profiles at build time. This behavior is intentional. To use this entitlement, either enable Push Notifications in the project editor's Capabilities pane, or manually add the entitlement to your entitlements file. For more information, see https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/HandlingRemoteNotifications.html#//apple_ref/doc/uid/TP40008194-CH6-SW1.After you’ve corrected the issues, you can upload a new binary to App Store Connect.

**Comment by lijogeorgep** [comment]
Log in to the Apple Developer Provisioning Portal: Go to the Apple Developer website (developer.apple.com) and sign in with your Apple Developer account.

Enable Push Notifications for your App ID: Navigate to the "Certificates, Identifiers & Profiles" section and select "App IDs" from the sidebar. Find your App ID and make sure it has the "Push Notifications" capability enabled. If it's not enabled, edit the App ID and enable the capability.

Generate a new Provisioning Profile: Once the Push Notifications capability is enabled for your App ID, you need to create a new Distribution provisioning profile. Go to the "Provisioning Profiles" section and select "Distribution" from the sidebar. Create a new provisioning profile for your app, making sure to select the correct App ID and enable the Push Notifications capability for it.

Download and install the new Provisioning Profile: After creating the provisioning profile, download it and double-click to install it on your development machine. This will make it available in Xcode for code signing.

Update your Xcode project settings: Open your Xcode project and go to the project settings. In the "Signing & Capabilities" tab, make sure you have selected the newly downloaded provisioning profile for the "Release" build configuration. This ensures that the correct entitlements are included in your app during the build process.

Verify entitlements file: If you already have an entitlements file in your Xcode project, make sure it includes the 'aps-environment' entitlement. If not, you can manually add it to the entitlements file. If you don't have an entitlements file, you can create one and add the 'aps-environment' entitlement.

Build and upload: Build your app using the updated settings and ensure that the 'aps-environment' entitlement is included in the app's signature. Once you have a valid binary, you can upload it to App Store Connect for review and submission to the App Store.

It's important to note that Xcode does not automatically copy the 'aps-environment' entitlement from provisioning profiles at build time, which is why you need to ensure the correct provisioning profile and entitlements are set up in your project.
